config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  get '/home', to: 'static_pages#home'
  get '/help', to:  'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'static_pages#home'

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><h2 class="text-white">Aplikace</h2></a>
    <button class="navbar-toggler col-md-2 bg-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      Menu
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item"><%= link_to "Domů", home_path, {:class => "nav-link"} %></li>
        <li class="nav-item"><%= link_to "Help", help_path, {:class => "nav-link"}%></li>
      </ul>
    <% if logged_in? %>
      <ul class="nav navbar-nav ms-auto">
        <li><%= link_to "Uživatelé", users_path, {:class => "nav-link"} %></li>
      </ul>
      <div>
        <button class="navbar-toggler col-md-2 bg-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#userContent"
                aria-controls="userContent" aria-expanded="false" aria-label="Toggle navigation">
          Uživatel
        </button>
        <div class="collapse navbar-collapse" id="userContent">
          <ul class="nav navbar-nav">
            <li class="nav-item"><%= link_to "Profil", current_user, {:class => "nav-link"} %></li>
            <li class="nav-item"><%= link_to "Nastavení", edit_user_path(current_user), {:class => "nav-link"} %></li>
            <li class="dropdown-divider"></li>
            <li class="nav-item"><%= link_to "Odhlásit", logout_path, method: :get, :class => "nav-link" %></li>
          </ul>
        </div>
      </div>
    <% else %>
      <ul class="nav navbar-nav ms-auto">
        <li class="nav-item"><%= link_to "Log In", login_path, {:class => "nav-link"} %></li>
      </ul>
    <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="UTF-8"></meta>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'bootstrap', 'data-turbolinks-track' => true %>
  </head>

  <body class="bg-secondary">
  <%= render 'layouts/nav' %>
  <div class="container text-white">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>